### ISSUE TITLE
デッキに編成していないスキルカードがシミュレーションに出現

### ISSUE THREAD

**Issue by Tetrapod-108** [katabami83/gakumas_contest_simulator#2]
![image](https://github.com/user-attachments/assets/5d6c31a7-bfc1-4c94-b213-af6aac2a3fc7)
こちらの画像の編成でシミュレーターを回したところ、編成していない「交わる感情＋」(新SSRサポカのスキルカード)の使用履歴がありました。
![image](https://github.com/user-attachments/assets/8ae1ef20-308f-4b6e-8746-1d5e51f55aef)
どちらに報告すればいいか分からなかったのでこちらに書き込ませていただきます。
既出でしたら申し訳ないです。

**Comment by katabami83** [comment]
報告ありがとうございます。
「お泊り猛勉強-/+」と「交わる感情-/+」のカードidが被っていて、読み込み時に上書きされてしまっていたことが原因でしたので修正しました。
他にもあったら、ここでもdiscord(raka06422)でも[スプシ](https://docs.google.com/spreadsheets/d/15J1iebMd_elVmBmBzCHHT2nLhSecFiuRdFKSZAo8CGs/edit?gid=1777197971#gid=1777197971)でも報告してもらえればと思います！

**Comment by Tetrapod-108** [comment]
シミュレーターいつも使わせて頂いてます！
ご対応いただきありがとうございました。
