### ISSUE TITLE
複数回スタックされたスキルカード「至高のエンタメ」は、効果を1つだけ得ることができます

### ISSUE THREAD

**Issue by kanon511** [katabami83/gakumas_contest_simulator#3]
![image](https://github.com/user-attachments/assets/8c8a9c98-64a4-4e93-811a-e699a0c01cc7)
7ターン目、9ターン目，前者は至高が1つしかなく、後者は至高が2つあるが、このアビリティのスコア増加は同様で、集中の低下により9ターン目の至高ダメージすら低くなっている。（両者も好調がある、绝好調がない）

**Comment by kanon511** [comment]
通常の状況は複数回ではありませんが、もし「国民的アイドル」がある、それはまだ可能です

**Comment by katabami83** [comment]
報告ありがとうございます。
全ての継続ステータス効果が重複していなかったため、重複数だけ発動するようにしました。

Thanks for the report.
All permanent status effects were not duplicated, so I have made sure that the number of duplicates are triggered.
![スクリーンショット 2024-08-08 180809](https://github.com/user-attachments/assets/44d936c9-ce84-46cb-a904-bcea69629f14)

![スクリーンショット 2024-08-08 180841](https://github.com/user-attachments/assets/6d6354bb-2e3e-4a40-96f5-0535f9a758c3)
