### ISSUE TITLE
休憩でターンを終了すると、ターン終了時効果が発動しない

### ISSUE THREAD

**Issue by CIkakan** [katabami83/gakumas_contest_simulator#7]
以下２つの画像のように、体力が切れて休憩(rest)を行う際、ターン終了時の処理(end_turn)がスキップされます。
(第6期ステージ3で体力を0で始めると簡単に再現されます)

好印象
![好印象](https://github.com/user-attachments/assets/d69a8b61-f296-43e2-8378-484195a79dcf)
天真爛漫
![天真爛漫](https://github.com/user-attachments/assets/13d6db58-6b0d-45ac-be56-0255e095a171)

**Comment by katabami83** [comment]
休憩したときにターン終了時の行動を設定していませんでした。
修正しました。
